@startuml
entity Users {
    +String address
    +String name
    +String email
    +String telephone
    +Int type
}

' Annotations and additional metadata
note right of Users::address
  PrimaryKey
  ColumnInfo(NOCASE)
  Description: EC-aдрес подписанта
end note

note right of Users::type
  Description: Техническое поле.
  0 - не мой адрес
  1 - мой адрес
  2 - мой текущий адрес
end note

@enduml
